### ISSUE TITLE
what is cnxn?

### ISSUE THREAD

**Issue by Andriuskislas** [svanoort/python-client-benchmarks#13]
When I was checking benchmarks report, I saw reuse of cnxn improves performance. I am curious to know what does it mean my cnxn ?

**Comment by svanoort** [comment]
This is short for "connection" -- HTTP uses a TCP connection, which can be created and used once for each request, but what browsers do more commonly is create a connection and use something called "keep alive" mode to reuse this for multiple requests.  This is because there is a 3-way back and forth handshake needed to create the request, which can be slow in high latency situations.   HTTPS requires a more complex process of negotiating encryption that is even more expensive, so reuse is critical there.
